<!DOCTYPE html>
<html lang="en">
<head>
<title>{% block title %}hexo-theme-rgb{% endblock %}</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href="favicon.ico?v=2">
{% block script %}
{% endblock %}
{% block css %}
{% endblock %}
</head>
<body>
{% block header %}
{% endblock %}
{% block content %}
{% endblock %}
{% block footer %}
{% endblock %}
</body>
{% block endscript %}
{% endblock %}
</html>
